set -e

## retry on failure

# allow showing hidden content
echo -e '\nc.ContentsManager.allow_hidden = True' >> /etc/jupyter/jupyter_server_config.py

# update & install conda packages
conda update --yes -n base conda
conda update --yes -c conda-forge jupyterlab
conda install --yes -c conda-forge jupyterlab-git
conda install --yes -c conda-forge jupytext
# clean all unused files
conda clean -all --yes --verbose

# modify login PATH env variable
echo -e 'CONDA_DIR=/opt/conda\nPATH="${CONDA_DIR}/bin:${PATH}"' > /etc/profile.d/add-conda-path.sh
# fix public GPG Key error when doing apt-get update
# ref: https://github.com/NVIDIA/nvidia-docker/issues/1631#issuecomment-1112828208
rm /etc/apt/sources.list.d/cuda.list
rm /etc/apt/sources.list.d/nvidia-ml.list
apt-key del 7fa2af80
apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/$distro/$arch/3bf863cc.pub
apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/7fa2af80.pub
# install graphviz, openssh-server
apt-get update --yes
apt-get install --yes --no-install-recommends graphviz
apt-get install --yes --no-install-recommends openssh-server
# clean
apt-get clean && rm -rf /var/lib/apt/lists/*

# change owner to jovyan
chown "${NB_USER}:${NB_GID}" .condarc .bash_history

# clear ipython folder (generated by Jupyter) and bash history, then exit
history -c && history -w && \
rm -rf .ipython .bash_history && \
exit
